In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import itertools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pylab import rcParams
import matplotlib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import random
from keras import Model
from keras.layers import Dense , Flatten,Concatenate, Embedding,Input
from keras.models import Sequential
from keras.regularizers import l1
from keras.layers.normalization import BatchNormalization
from keras import backend as K
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from sklearn.ensemble import IsolationForest
import tensorflow as tf
seed = 2891  
random.seed(seed)
np.random.seed(seed)
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
train_new = pd.read_csv('Train.csv')
band_names = [l.strip() for l in open('bandnames.txt', 'r').readlines()]
ss = pd.read_csv('SampleSubmission.csv')

In [3]:
def process_im(fid, folder='image_arrays_train'):
  fn = f'{folder}/{fid}.npy'
  arr = np.load(fn)
  bands_of_interest = ['S2_B1','S2_B2','S2_B3','S2_B4','S2_B5','S2_B6','S2_B7','S2_B8','S2_B8A','S2_B9','S2_B10',
                       'S2_B11','S2_B12','S2_QA10','S2_QA20' ,'S2_QA60','CLIM_aet','CLIM_def','CLIM_pdsi','CLIM_pet',
                       'CLIM_pr','CLIM_ro','CLIM_soil' ,'CLIM_srad' ,'CLIM_swe','CLIM_tmmn','CLIM_tmmx',
                       'CLIM_vap','CLIM_vpd','CLIM_vs']
  
  values = {}
  for month in range(12):
    bns = [str(month) + '_' + b for b in bands_of_interest] # Bands of interest for this month 
    idxs = np.where(np.isin(band_names, bns)) # Index of these bands
    vs = arr[idxs, 20, 20] # Sample the im at the center point
    for bn, v in zip(bns, vs[0]):
      values[bn] = v
  return values
def to_submit(pred_y,name_out):
    y_predict = list(itertools.islice(pred_y, test.shape[0]))
    y_predict = pd.DataFrame(prepro_y.inverse_transform(np.array(y_predict).reshape(len(y_predict),1)), columns = ['Yield'])
    y_predict = y_predict.join(t)   #Field_ID
    y_predic = y_predict[['Field_ID', 'Yield']]
    y_predic.to_csv(name_out + '.csv',index=False)
def input_fn_new(data_set, training = True):
    continuous_cols = {k: tf.constant(data_set[k].values) for k in FEATURES}
    
    categorical_cols = {k: tf.SparseTensor(
        indices=[[i, 0] for i in range(data_set[k].size)], values = data_set[k].values, dense_shape = [data_set[k].size, 1]) for k in FEATURES_CAT}

    # Merges the two dictionaries into one.
    feature_cols = dict(list(continuous_cols.items()) + list(categorical_cols.items()))
    
    if training == True:
        # Converts the label column into a constant Tensor.
        label = tf.constant(data_set[LABEL].values)

        # Returns the feature columns and the label.
        return feature_cols, label
    
    return feature_cols
train_sampled = pd.DataFrame([process_im(fid) for fid in train_new['Field_ID'].values])

# Add in the field ID and yield
train_sampled['Field_ID'] = train_new['Field_ID'].values
train_sampled['Yield'] = train_new['Yield'].values
# train_sampled.head()
test_sampled = pd.DataFrame([process_im(fid, folder='image_arrays_test') for fid in ss['Field_ID'].values])
# test_sampled['Field_ID'] = ss['Field_ID']
# test_sampled['Yield'] = 0
# Example
# process_im('35AFSDD')

In [4]:
train = train_sampled.copy()
test = test_sampled.copy()
add_info = pd.read_csv('fields_w_additional_info.csv')

In [5]:
# add_info.isna().sum()

In [6]:

# # Import and split
# # train = pd.read_csv('train_df_cust.csv')
# train_numerical = train.select_dtypes(exclude=['object'])
# train_categoric = train.select_dtypes(include=['object'])
# train = train_numerical.merge(train_categoric, left_index = True, right_index = True) 

# # test = pd.read_csv('test_df_cust.csv')
# Yield_ID = ss.Field_ID
# test_numerical = test.select_dtypes(exclude=['object'])
# test_categoric = test.select_dtypes(include=['object'])
# test = test_numerical.merge(test_categoric, left_index = True, right_index = True) 
# # Removie the outliers

# clf = IsolationForest(max_samples = 100, random_state = 42)
# clf.fit(train_numerical)
# y_noano = clf.predict(train_numerical)
# y_noano = pd.DataFrame(y_noano, columns = ['Top'])
# y_noano[y_noano['Top'] == 1].index.values

# train_numerical = train_numerical.iloc[y_noano[y_noano['Top'] == 1].index.values]
# train_numerical.reset_index(drop = True, inplace = True)

# train_categoric = train_categoric.iloc[y_noano[y_noano['Top'] == 1].index.values]
# train_categoric.reset_index(drop = True, inplace = True)

# train = train.iloc[y_noano[y_noano['Top'] == 1].index.values]
train.reset_index(drop = True, inplace = True)

In [11]:
test_numerical = test.select_dtypes(exclude=['object'])
test_categoric = test.select_dtypes(include=['object'])
train_numerical = train.select_dtypes(exclude=['object'])
train_categoric = train.select_dtypes(include=['object'])
col_train = list(train.columns)
col_train_bis = list(train.columns)
col_train_bis.remove('Yield')

col_train_num = list(train_numerical.columns)
col_train_num_bis = list(train_numerical.columns)

col_train_cat = list(train_categoric.columns)

col_train_num_bis.remove('Yield')

mat_train = np.matrix(train_numerical)
mat_test  = np.matrix(test_numerical)
mat_new = np.matrix(train_numerical.drop('Yield',axis = 1))
mat_y = np.array(train.Yield)

prepro_y = MinMaxScaler()
prepro_y.fit(mat_y.reshape(2977,1))

prepro = MinMaxScaler()
prepro.fit(mat_train)

prepro_test = MinMaxScaler()
prepro_test.fit(mat_new)

train_num_scale = pd.DataFrame(prepro.transform(mat_train),columns = col_train_num)
test_num_scale  = pd.DataFrame(prepro_test.transform(mat_test),columns = col_train_num_bis)

train[col_train_num] = pd.DataFrame(prepro.transform(mat_train),columns = col_train_num)
test[col_train_num_bis]  = test_num_scale

In [12]:
# # List of features
# COLUMNS = col_train_num
# FEATURES = col_train_num_bis
# LABEL = "Yield"

# FEATURES_CAT = col_train_cat

# engineered_features = []

# for continuous_feature in FEATURES:
#     engineered_features.append(
#         tf.feature_column.numeric_column(continuous_feature))

# for categorical_feature in FEATURES_CAT:
#     sparse_column = tf.feature_column.categorical_column_with_hash_bucket(
#         categorical_feature, hash_bucket_size=1000)

#     engineered_features.append(tf.feature_column.embedding_column(categorical_column=sparse_column, dimension=16,combiner="sum"))
                                 
# # Training set and Prediction set with the features to predict
# training_set = train[FEATURES + FEATURES_CAT]
# prediction_set = train.Yield

# # Train and Test 
# x_train, x_test, y_train, y_test = train_test_split(training_set[FEATURES + FEATURES_CAT] ,
#                                                     prediction_set, test_size=0.33, random_state=42)
# y_train = pd.DataFrame(y_train, columns = [LABEL])
# training_set = pd.DataFrame(x_train, columns = FEATURES + FEATURES_CAT).merge(y_train, left_index = True, right_index = True)

# # Training for submission
# training_sub = training_set[FEATURES] # + FEATURES_CAT]
# testing_sub = test[FEATURES] # + FEATURES_CAT]

In [13]:
# # a[0]['Field_ID']
from keras.utils import to_categorical
# to_categorical(train['Field_ID'])

In [14]:
total = add_info['Field_ID'].values.copy()
par = train['Field_ID'].values.copy()
sar = ss.Field_ID.values


In [15]:
tot = par.tolist()+sar.tolist()

In [17]:
# par

In [18]:
# len(one_hot_encode[0])

In [19]:
mapping = {}
for x in range(len(tot)):
  mapping[tot[x]] = x

# integer representation
for x in range(len(tot)):
  tot[x] = mapping[tot[x]]


one_hot_encode = to_categorical(tot)
print(one_hot_encode)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [21]:
# mapping[ss.Field_ID[55]]
# one_hot_encode.shape
# len(par)

In [22]:
no_of_unique_cat  = len(tot)
embedding_size = min(np.ceil((no_of_unique_cat)/2), 50 )
embedding_size = int(embedding_size)

In [23]:
num_data = train[col_train_num_bis]

In [24]:
inp_cat_data = Input(shape=(no_of_unique_cat,))
inp_num_data = Input(shape=(num_data.shape[1],))
# Bind nulti_hot to embedding layer
emb = Embedding(input_dim=no_of_unique_cat, output_dim=embedding_size)(inp_cat_data)  
# Also you need flatten embedded output of shape (?,3,2) to (?, 6) -
# otherwise it's not possible to concatenate it with inp_num_data
flatten = Flatten()(emb)
# Concatenate two layers
conc = Concatenate()([flatten, inp_num_data])
# x = BatchNormalization()(conc)
dense1 = Dense(1148, activation='relu')(conc)
# x =  BatchNormalization()(dense1)
dense2 = Dense(512,activation = 'relu')(dense1)
dense3 = Dense(128,activation = 'relu')(dense2)
out = Dense(1, activation='linear')(dense3)
model = Model(inputs=[inp_cat_data, inp_num_data], outputs=out)
from tensorflow import keras
opt = keras.optimizers.Adam(learning_rate=0.01)
# model.compile(optimizer='adam',loss='mse',metrics=['mean_squared_error'])
early_stopping = EarlyStopping(monitor='val_loss', patience=5, mode='min',restore_best_weights=True)
save_best = ModelCheckpoint('checkpoint', save_best_only=True, 
                               monitor='val_loss', mode='min')
model.compile(optimizer=opt,
              loss=keras.losses.mean_squared_error,
              metrics=[keras.metrics.mean_squared_error])

In [157]:
# test

In [25]:
model.fit([one_hot_encode[:len(par)], train[col_train_num_bis]] ,train['Yield'] , validation_split= 0.2,epochs=30,batch_size=100,verbose=1 , 
                 callbacks=[early_stopping,save_best])

Epoch 1/30
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
24/24 [==============================] - ETA: 0s - loss: 62289.7812 - mean_squared_error: 62289.7812WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x000002318E6A3798> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRA

24/24 [==============================] - ETA: 0s - loss: 0.0256 - mean_squared_error: 0.0256WARNING:tensorflow:AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x000002318EBF8678> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
INFO:tensorflow:Assets written to: checkpoint\assets
24/24 [==============================] - 63s 3s/step - loss: 0.0256 - mean_sq

In [26]:
# to_submit(pred_y,name_out)

In [27]:
# ss.Field_ID
# (train_sampled.Field_ID == 'E9UZCEA' ).any()
# train_sampled
# (train_new[train_new.Quality>1].Field_ID == 'E9UZCEA').any() 


# Model

In [28]:
# # training_set1[0]
# for x in range(len(sar)):
#    sar[x] = mapping[sar[x]]
# one_he = to_categorical(sar)

In [29]:
# add_info.Field_ID.shape

In [30]:
# train_sampled.shape

In [31]:
# ss.shape
y_predict = model.predict([one_hot_encode[len(par):], test[col_train_num_bis]])


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [32]:
# to_categorical(sar)
# y_predict
ss = pd.read_csv('SampleSubmission.csv')
t = ss.Field_ID
to_submit(y_predict, "submission_continuous10")

In [33]:
chec = pd.read_csv('submission_continuous10.csv')
chec['Yield'] = (chec['Yield']).clip(lower = 0)
# (chec['Yield']<0).any()

In [34]:
chec.to_csv('mod4_sub_0.csv',index = False)

In [110]:
prepro_y1 = MinMaxScaler()
prepro_y1.fit(mat_y.reshape(2642,1))
prepro_y1.inverse_transform(np.array(y_predict).reshape(len(y_predict),1))

array([[ 2.1022296 ],
       [ 2.0850935 ],
       [ 1.2661266 ],
       ...,
       [-0.32159072],
       [ 1.5196413 ],
       [-0.6216494 ]], dtype=float32)

In [129]:
import seaborn as sns
(mat_y == 0).sum()

16

In [130]:
# train.Yield
# chec = pd.read_csv('mod_sub_abs.csv')
# chec
chec

Field_ID     Yield
0     E9UZCEA  2.102230
1     1WGGS1Q  2.085094
2     EG2KXE2  1.266127
3     HC3GQXF  2.783577
4     7AK6GFK  2.277250
...       ...       ...
1050  3H89LWV  0.000000
1051  I6EYSGB  0.000000
1052  XOEIR44  0.000000
1053  YB307JG  1.519641
1054  8TT86NF  0.000000

[1055 rows x 2 columns]